print(bool(1))
print(bool(0))
print(bool(0.01))
print(bool((1,2)))
print(bool((0,0)))
print(bool('string'))
print(bool('0'))
print(bool(''))
print(bool([0,0]))
print(bool({0}))
print(bool({}))
x = True
y = False
print(int(x))
print(int(y))
print(int(x and y))
print(int(x or y))
print(int(x + y))
print(int(x - y))
print(int(x * y))
x = eval(input())
y = eval(input())
print(int(x))
print(int(y))
print(int(x and y))
print(int(x or y))
print(int(x + y))
print(int(x - y))
print(int(x * y))
